apiVersion: apps/v1
kind: Deployment
metadata:
  name: myargoapp
spec:
  selector:
    matchLabels:
      app: myargoapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myargoapp
    spec:
      containers:
        - name: myargoapp
          image: judebevan/hello-world:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
